// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			angrynerdbot_w.c
// Function:		weapon weights for AngryNerdBot
// Programmer:		Q3BD
// Last update:		Sunday, November 06, 2016 at 09:12:52
//===========================================================================


#include "inv.h"


#define W_GAUNTLET				50
#define W_SHOTGUN				50
#define W_MACHINEGUN			200
#define W_GRENADELAUNCHER		400
#define W_ROCKETLAUNCHER		200
#define W_RAILGUN				100
#define W_BFG10K				100
#define W_LIGHTNING				400
#define W_PLASMAGUN				400
#define W_GRAPPLE				15

#include "fw_weap.c"


