// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			angrynerdbot_w.c
// Function:		weapon weights for AngryNerdBot
// Programmer:		Q3BD
// Last update:		Sunday, November 06, 2016 at 09:12:52
//===========================================================================


#include "inv.h"


#define W_GAUNTLET				99
#define W_SHOTGUN				750
#define W_MACHINEGUN			20
#define W_GRENADELAUNCHER		140
#define W_ROCKETLAUNCHER		400
#define W_RAILGUN				20
#define W_BFG10K				95
#define W_LIGHTNING				80
#define W_PLASMAGUN				250
#define W_GRAPPLE				15

//
#include "fw_weap.c"


